version: "3"

services:
  laravel-app:
    container_name: prova-pedro--laravel
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - app-network

  mysql-app:
    container_name: prova-pedro--mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: before
      MYSQL_ROOT_PASSWORD: before
    networks:
      - app-network

networks:
  app-network:
    driver: bridge